spring:
  application:
    name: "auth-service"
  profiles:
    active: "service"
  config:
    import: "optional:configserver:http://localhost:8088"


#sporing :
#   application:
#     name: SECURITY_SERVICE
#
#
#eureka :
#  client :
#    service_url : http://localhost:8761/eureka/
#
#server:
#  port : 9090